global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'vdvnet'
rule_files:
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['mon_node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['mon_cadvisor:8080']

  - job_name: 'traefik'
    basic_auth:
      username: user
      password: password
    static_configs:
            - targets: ['traefik:8082']
