log:
  level: info

entryPoints:
  web:
    address: :80
  web-secured:
    address: :443
  dashboard:
    address: :8080
  metrics:
    address: :8082

certificatesResolvers:
  mytlschallenge:
    acme:
      tlschallenge: true
      email: oliver@van-der-velde.net
      storage: /etc/traefik/ACME/acme.json

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: web
  file:
    directory: /etc/traefik/dynamic/

api: {}

metrics:
  prometheus:
          #    entryPoint: metrics
    manualRouting: true
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
