---
version: '3'

services:
  mon_prometheus:
    image: prom/prometheus:latest
    container_name: mon_prometheus
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.prometheus-https.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus-http.entrypoints=web"
      - "traefik.http.routers.prometheus-http.rule=Host(`prometheus.van-der-velde.net`)" #Domain anpassen
      - "traefik.http.routers.prometheus-http.middlewares=prometheus-https@docker"
      - "traefik.http.routers.prometheus.entrypoints=web-secured"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.van-der-velde.net`)" #Domain anpassen
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.prometheus.middlewares=secHeaders@file"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=authProm"
      - "traefik.http.middlewares.authProm.basicauth.users=olveld:$$apr1$$Lk3/sSgj$$MczOeSpF4avx07tOTK7Eu/"
    volumes:
      - /var/clouddata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mon_node-exporter
      - mon_cadvisor
    networks:
      - web
      - backend

  mon_node-exporter:
    image: prom/node-exporter:latest
    container_name: mon_node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - backend

  mon_cadvisor:
    image: google/cadvisor:latest
    container_name: mon_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend

  mon_grafana:
    image: grafana/grafana:latest
    container_name: mon_grafana
    restart: unless-stopped
    volumes:
      - /var/clouddata/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "5003" # USER ID des Docker Users anpassen
    depends_on:
      - mon_prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.grafana-https.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana-http.entrypoints=web"
      - "traefik.http.routers.grafana-http.rule=Host(`monitoring.van-der-velde.net`)" #Domain anpassen
      - "traefik.http.routers.grafana-http.middlewares=grafana-https@docker"
      - "traefik.http.routers.grafana.entrypoints=web-secured"
      - "traefik.http.routers.grafana.rule=Host(`monitoring.van-der-velde.net`)" #Domain anpassen
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.grafana.middlewares=secHeaders@file"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - web
      - backend

networks:
  web:
    external: true
  backend:
    external: false
